### ISSUE TITLE
Error in premade configure/Makefile

### ISSUE THREAD

**Issue by sdwfrost** [gtonkinhill/pairsnp#2]
When compiling on Ubuntu 16.04, I need to run `automake --add-missing` in order to get the build process to work.

**Comment by gtonkinhill** [comment]
This was an annoying issue with github not updating the time stamps. It could be fixed by running touch ./cpp/* instead of automake but hopefully I've managed to update the timestamps in the github repo. The better way and what I'll do ultimately is have a zip file for people to download.
