### ISSUE TITLE
Can't use float as index in Python code for INITIALISATION_LENGTH

### ISSUE THREAD

**Issue by sdwfrost** [gtonkinhill/pairsnp#4]
You can't use scientific notation for `INITIALISATION_LENGTH`, which should read

```python
INITIALISATION_LENGTH = 100000`
```

You should be able to set/override this in the command line too.

**Comment by gtonkinhill** [comment]
I've updated it as suggested but haven't added a command to override it as if it is not big enough the array will be extended. I don't think the initial size is so big that it would cause anyone issues but am happy to be corrected.
