### ISSUE TITLE
Dependency on aclocal-1.16

### ISSUE THREAD

**Issue by sdwfrost** [gtonkinhill/pairsnp#5]
Hi @gtonkinhill 

The pre-build configure script depends on a specific version of aclocal, and so doesn't compile OOTB on my OSX machine (even though aclocal is installed)

```sh
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh /Users/simon/Projects/pairsnp/cpp/missing aclocal-1.16 
/Users/simon/Projects/pairsnp/cpp/missing: line 81: aclocal-1.16: command not found
WARNING: 'aclocal-1.16' is missing on your system.
         You should only need it if you modified 'acinclude.m4' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'aclocal' program is part of the GNU Automake package:
         <https://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <https://www.gnu.org/software/autoconf>
         <https://www.gnu.org/software/m4/>
         <https://www.perl.org/>
make: *** [aclocal.m4] Error 127
Simons-Mac-mini:cpp simon$ which aclocal
/usr/local/bin/aclocal
```

**Comment by gtonkinhill** [comment]
Hmm this looks like the timestamp issue again. Try running touch * on the cpp directory. I think I need to create a zip file to get around this and make installing easier.On 11 Aug 2018 07:03, Simon Frost <notifications@github.com> wrote:Hi @gtonkinhill
The pre-build configure script depends on a specific version of aclocal, and so doesn't compile OOTB on my OSX machine (even though aclocal is installed)
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh /Users/simon/Projects/pairsnp/cpp/missing aclocal-1.16 
/Users/simon/Projects/pairsnp/cpp/missing: line 81: aclocal-1.16: command not found
WARNING: 'aclocal-1.16' is missing on your system.
         You should only need it if you modified 'acinclude.m4' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'aclocal' program is part of the GNU Automake package:
         <https://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <https://www.gnu.org/software/autoconf>
         <https://www.gnu.org/software/m4/>
         <https://www.perl.org/>
make: *** [aclocal.m4] Error 127
Simons-Mac-mini:cpp simon$ which aclocal
/usr/local/bin/aclocal

**Comment by sdwfrost** [comment]
Yup, that fixed it. The source should still work, and you should save zip files for when you have a first release.
